#### - Sobhan Moradian Daghigh
#### 
#### - 1/6/2022
#### 
#### - ML - EX03 - Q2

In [231]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from xgboost import XGBClassifier

In [233]:
train = pd.read_csv('./dataset/data_train.csv', names=range(17),index_col=False)
test = pd.read_csv('./dataset/data_test.csv', names=range(17),index_col=False)
train.head()

0    1   2    3    4    5    6    7   8   9    10  11   12  13   14  15  16
0  47  100  27   81   57   37   26    0   0  23   56  53  100  90   40  98   8
1   0   89  27  100   42   75   29   45  15  15   37   0   69   2  100   6   2
2   0   57  31   68   72   90  100  100  76  75   50  51   28  25   16   0   1
3   0  100   7   92    5   68   19   45  86  34  100  45   74  23   67   0   4
4   0   67  49   83  100  100   81   80  60  60   40  40   33  20   47   0   1

In [68]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7494 entries, 0 to 7493
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7494 non-null   int64
 1   1       7494 non-null   int64
 2   2       7494 non-null   int64
 3   3       7494 non-null   int64
 4   4       7494 non-null   int64
 5   5       7494 non-null   int64
 6   6       7494 non-null   int64
 7   7       7494 non-null   int64
 8   8       7494 non-null   int64
 9   9       7494 non-null   int64
 10  10      7494 non-null   int64
 11  11      7494 non-null   int64
 12  12      7494 non-null   int64
 13  13      7494 non-null   int64
 14  14      7494 non-null   int64
 15  15      7494 non-null   int64
 16  16      7494 non-null   int64
dtypes: int64(17)
memory usage: 995.4 KB


### Part A.

In [69]:
estimators = 15
features_size = 3
max_depth = 3

In [70]:
rfc = RandomForestClassifier(n_estimators=estimators, max_depth= max_depth, max_features=features_size, random_state=0)
rfc.fit(train.iloc[:, :-1], train.iloc[:, -1])
predictions = rfc.predict(test.iloc[:, :-1])
print("The accuracy is: {}".format(round(rfc.score(test.iloc[:, :-1], test.iloc[:, -1]), 3)))
print("The f1-score is: {}".format(round(f1_score(test.iloc[:, -1], predictions, average='weighted'), 3)))

The accuracy is: 0.791
The f1-score is: 0.786


In [71]:
print(confusion_matrix(test.iloc[:, -1], predictions))

[[315   4   0   0   0   0   1   3  40   0]
 [  0 188 135   1   2   0   0   0   0  38]
 [  0  18 342   1   1   0   0   2   0   0]
 [  0   7   0 328   0   0   0   0   0   1]
 [  0   2   0   1 354   0   0   0   0   7]
 [  0   0   0 116  13 162   0   0   6  38]
 [  3   0   2   3   0   0 297  29   2   0]
 [  0  22  10   3   0   3   3 294   0  29]
 [ 16   0   0   0   0  12   2  22 283   1]
 [  0  52   0  63  13   0   2   0   2 204]]


### Part B.

In [72]:
estimators = 10

In [89]:
abc = AdaBoostClassifier(n_estimators=estimators, random_state=0, learning_rate=0.3)
abc.fit(train.iloc[:, :-1], train.iloc[:, -1])
predictions = abc.predict(test.iloc[:, :-1])
print("The accuracy is: {}".format(round(abc.score(test.iloc[:, :-1], test.iloc[:, -1]), 3)))
print("The f1-score is: {}".format(round(f1_score(test.iloc[:, -1], predictions, average='weighted'), 3)))

The accuracy is: 0.62
The f1-score is: 0.579


### Part C.

In [91]:
estimators = [5, 20, 50]

In [95]:
for estim in estimators:
    abc = AdaBoostClassifier(n_estimators=estim, random_state=0, learning_rate=0.3)
    abc.fit(train.iloc[:, :-1], train.iloc[:, -1])
    predictions = abc.predict(test.iloc[:, :-1])
    print("The estimator is {}:".format(estim))
    print("\tThe accuracy is: {}".format(round(abc.score(test.iloc[:, :-1], test.iloc[:, -1]), 3)))
    print("\tThe f1-score is: {}".format(round(f1_score(test.iloc[:, -1], predictions, average='weighted'), 3)))
    print("\n")

The estimator is 5:
	The accuracy is: 0.536
	The f1-score is: 0.456


The estimator is 20:
	The accuracy is: 0.646
	The f1-score is: 0.601


The estimator is 50:
	The accuracy is: 0.706
	The f1-score is: 0.687




### Part D.

In [224]:
params = [
    {"eta": [1, 0.5, 0.1]},
    {"gamma": [0, 0.1, 0.2]},
    {"max_depth": [3, 4, 5, 6]},
    {"min_child_weight": [0, 0.3, 0.7]},
    {"subsample": [0.5, 0.7, 0.9]},
    {"refresh_leaf": [0, 1]},
    {"colsample_bytree": [0.3, 0.5, 0.7]},
]

In [237]:
xgbc = XGBClassifier(use_label_encoder=False, eval_metric='rmse')
gs = GridSearchCV(xgbc, params, cv=3, verbose=1)
gs.fit(train.iloc[:, :-1], train.iloc[:, -1])

Fitting 3 folds for each of 21 candidates, totalling 63 fits


GridSearchCV(cv=3,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     enable_categorical=False,
                                     eval_metric='rmse', gamma=None,
                                     gpu_id=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_delta_step=None,
                                     max_depth=None, min_child_weight=None,
                                     missing=nan, monoton...
                                     random_state=None, reg_alpha=None,
                                     reg_lambda=None, scale_pos_weight=None,
                                     subsample=None, tree_method=None,
                          

In [253]:
results = pd.DataFrame(gs.cv_results_)
results = results.reset_index().sort_values(['rank_test_score', 'index'])
results.reset_index(inplace=True)
pd.DataFrame([results.loc[:, x] for x in ['params', 'mean_test_score']]).T.head(10)

params mean_test_score
0  {'colsample_bytree': 0.5}         0.99106
1         {'subsample': 0.7}        0.990526
2  {'colsample_bytree': 0.3}        0.989992
3           {'max_depth': 5}        0.989725
4  {'colsample_bytree': 0.7}        0.989725
5           {'max_depth': 4}        0.989592
6  {'min_child_weight': 0.7}        0.989325
7               {'eta': 0.5}        0.989191
8               {'gamma': 0}        0.989191
9           {'max_depth': 6}        0.989191

In [261]:
xgbc = XGBClassifier(
    use_label_encoder=False, 
    eval_metric='rmse',
    eta='0.5',
    max_depth='5',
    subsample='0.7',
    colsample_bytree='0.5'
)
xgbc.fit(train.iloc[:, :-1], train.iloc[:, -1])
predictions = xgbc.predict(test.iloc[:, :-1])
print("The accuracy is: {}".format(round(xgbc.score(test.iloc[:, :-1], test.iloc[:, -1]), 3)))
print("The f1-score is: {}".format(round(f1_score(test.iloc[:, -1], predictions, average='weighted'), 3)))

The accuracy is: 0.973
The f1-score is: 0.973
